name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t healthcare-agent .

      - name: Tag image
        run: docker tag healthcare-agent:latest 843348559248.dkr.ecr.ap-south-1.amazonaws.com/healthcare-agent:latest

      - name: Push image
        run: docker push 843348559248.dkr.ecr.ap-south-1.amazonaws.com/healthcare-agent:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster healthcare-cluster-1 \
            --service healthcare-service \
            --force-new-deployment \
            --region ap-south-1